ALTER TABLE ns_notes ADD COLUMN is_private BOOLEAN DEFAULT TRUE;

CREATE INDEX ON ns_notes (is_private);

CREATE TABLE ns_notes_share (
	id UUID PRIMARY KEY,
	note_id UUID REFERENCES ns_notes (id) ON UPDATE CASCADE ON DELETE CASCADE,
	user_id UUID REFERENCES ns_users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	shared_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ns_notes_favorites (
	id UUID PRIMARY KEY,
	note_id UUID REFERENCES ns_notes (id) ON UPDATE CASCADE ON DELETE CASCADE,
	user_id UUID REFERENCES ns_users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);